//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// WeldEvaluation.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_WELDEVALUATION_FORM         101
#define IDR_MAINFRAME                   128
#define IDR_WeldEvaluationTYPE          130
#define IDS_PROPATYFILENAME             150
#define IDS_PROJECTFILENAME             151
#define IDS_PROJECTFILE_VERSION         152
#define IDS_PARAMETERFILE_VERSION       153
#define IDS_REGTEST_LABEL               200
#define IDS_PROPTAB_RESIN               210
#define IDS_PROPTAB_METAL               211
#define IDS_PROPTAB_RESULT              212
#define IDS_PROPTAB_OVERALL             213
#define IDS_OPRTAB_INIT                 220
#define IDS_OPRTAB_SETTING              221
#define IDS_OPRTAB_SCAN                 222
#define IDS_OPRTAB_ANARIZE              223
#define IDS_New                         224
#define IDS_NEW                         224
#define IDS_LBL_FOLDERSELECT            250
#define IDD_PROPTAB_PAGE_PARAM          310
#define IDD_PROPTAB_PAGE_SETTING        311
#define IDD_OPERTAB_PAGE_ANALIZE        312
#define IDD_OPERTAB_PAGE_SCAN           313
#define IDD_OPERTAB_PAGE_SETTING        314
#define IDD_OPERTAB_PAGE_INITIALIZE     315
#define IDD_STATUS_DLG                  316
#define IDD_GRAPH_WIND                  319
#define IDD_IMAGE_WIND                  320
#define IDD_PROGRESS_DLG                321
#define IDD_SPECTRAL_DLG                324
#define IDR_POPUP_MENU                  329
#define IDM_PROPUPDATE                  500
#define IDM_OPRTUPDATE                  501
#define IDM_CHECKOFUPDATE               502
#define IDM_MAKEFOLDER                  503
#define IDM_EXISTSCANIMAGE              504
#define IDM_EXISTWBSCANFILE             505
#define IDS_PREPANING                   506
#define IDM_SCANNING                    507
#define IDM_SCAN_CANCELD                508
#define IDM_SCAN_SUCCESS                509
#define IDM_RESULT_READ_TITLE           510
#define IDM_RESULT_READ_INIT            511
#define IDM_RESULT_READING              512
#define IDM_PRJREGIST_SUCCESS           513
#define IDM_PRJREGIST_OVERWRITE         514
#define IDM_PRJREGIST_EXISTUPDATE       515
#define IDM_ANALYZE_SUCCESS             516
#define IDS_EXIST_REPAIRABLEDATA        517
#define IDS_REPAIR_COMPLEAT             518
#define IDM_CHANGED_NUMBEROFCLASS       519
#define IDM_DELETE                      520
#define IDM_DELETE_ACTIVEPROJECT        521
#define IDM_INVERS_SUCCESS              522
#define IDM_DELETED_ANALIZEDATA         523
#define IDM_REANALIZE_REQUEST           524
#define IDM_ERR_NOTOPEN_REGTEST         700
#define IDM_ERR_SCAN                    701
#define IDM_ERR_PROJECT_SAVE            702
#define IDM_ERR_NOT_ANALYZE             703
#define IDM_ERR_FAIL_REGIST             704
#define IDM_ERR_NOTEXIST_ANALIZEDATA    705
#define IDM_ERR_INVERS_FAIL             706
#define IDM_ERR_FAILDCREATEIMAGE        707
#define IDF_JOININGRETIO                900
#define IDF_JOININGCOLOR                901
#define IDC_BTN_NEWPRJ                  1000
#define IDC_TAB_OPERATION               1002
#define IDC_TAB_PROPATY                 1003
#define IDC_EDT_JOINRATIO               1005
#define IDC_SPIN_NUMOFCLASS             1006
#define IDC_LST_REGIST_TEST             1007
#define IDC_STC_OPRTABPAG_CLIENT        1008
#define IDC_STC_PROPTABPAG_CLIENT       1009
#define IDC_BTN_PROP_UPDATE             1010
#define IDC_BTN_PROP_CANCEL             1011
#define IDC_STC_RESULTIMG_VIEW          1012
#define IDC_STC_METALIMG_VIEW           1013
#define IDC_STC_RESINIMG_VIEW           1014
#define IDC_STC_JOINRATIO_LABEL         1016
#define IDC_STC_JOINRATIO_UNIT          1017
#define IDC_STC_REGFOLDER_LABEL         1018
#define IDC_STC_JOINRATIO_TARGET_LABEL  1018
#define IDC_EDT_REGFOLDER               1019
#define IDC_BUN_REGFOLDER_FIND          1020
#define IDC_STC_WBFILENAME_LABEL        1021
#define IDC_EDT_WBFILENAME              1022
#define IDC_STC_NUMBEROFOVERRAPPINGPIXEL_LABEL 1023
#define IDC_EDT_NUMBEROFOVERRAPPINGPIXEL 1024
#define IDC_SPN__NUMBEROFOVERRAPPINGPIXEL 1025
#define IDC_STC_INTEGRATIONTIME_LABEL   1026
#define IDC_EDT_INTEGRATIONTIME         1027
#define IDC_SPN_INTEGRATIONTIME         1028
#define IDC_STC_RESOLUTION_HOLIZONTAL_LABEL 1029
#define IDC_EDT_RESOLUTION_HOLIZONTAL   1030
#define IDC_SPN_RESOLUTION_HOLIZONTAL   1031
#define IDC_STC_RESOLUTION_LABEL        1032
#define IDC_EDT_RESOLUTION_VERTICAL     1033
#define IDC_SPN_RESOLUTION_VERTICAL     1034
#define IDC_STC_RESOLUTION_VERTICAL_LABEL 1035
#define IDC_SBR_SETTING                 1036
#define IDC_STC_NUMOFCLASS_LABEL        1037
#define IDC_EDT_NUMOFCLASS              1038
#define IDC_BTN_SECTIONSPECTRUMDISPLAY  1039
#define IDC_RDO_RESIN_METHOD1           1040
#define IDC_RDO_RESIN_METHOD2           1041
#define IDC_BTN_RESINANALIZE            1042
#define IDC_RDO_METAL_METHOD1           1043
#define IDC_RDO_METAL_METHOD2           1044
#define IDC_BTN_METALANALIZE            1045
#define IDC_RDO_RESINSCAN               1046
#define IDC_RDO_RESINCLASRESULT         1047
#define IDC_RDO_METALSCAN               1048
#define IDC_RDO_METALCLASRESULT         1049
#define IDC_EDT_TESTNAME                1050
#define IDC_RDO_JOINT_METHOD1           1051
#define IDC_RDO_JOINT_METHOD2           1052
#define IDC_BTN_SCAN                    1053
#define IDC_RDO_JOINTRESULTCLASRESULT   1054
#define IDC_BTN_CANCEL                  1055
#define IDC_STC_SCANFRAME               1056
#define IDC_BTN_JOINTANALIZE            1057
#define IDC_RDO_REGIN                   1058
#define IDC_RDO_METAL                   1059
#define IDC_RSO_RESULT                  1060
#define IDC_STC_TESTNAME                1061
#define IDC_BTN_REGIST                  1062
#define IDC_BTN_IMAGEOUT                1063
#define IDC_STC_WHITEBARANCE            1064
#define IDC_BTN_WHITEBARANCE            1065
#define IDC_STC_RESIN_FRAME             1066
#define IDC_STC_METAL_FRAME             1067
#define IDC_STC_VIEWCHANGE_FRAME        1068
#define IDC_RDO_JOINTRESULTSCAN         1069
#define IDC_STC_REGIN_LABEL             1070
#define IDC_STC_METAL_LABEL             1071
#define IDC_STC_JOINTRESULT_LABEL       1072
#define IDC_EDT_STATUS                  1073
#define IDC_STC_JOINT_FRAME             1074
#define IDC_CMB_JOINRATIO_TARGET_LABEL  1075
#define IDC_STC_GRAPH                   1076
#define IDC_STC_GRAPH_WND               1077
#define IDC_STC_STATUS                  1078
#define IDC_PRO_STATUS                  1079
#define IDC_STC_IDCOLOR                 1080
#define IDC_STC_MESSAGE                 1081
#define IDC_MSG_FEILD                   1082
#define IDC_BTN_INVERS                  1083
#define IDC_BUTTON1                     1084
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_PROJECT_DELETE               32773
#define ID_PROJECT_OPEN                 32775
#define IDS_PROJECT_OPEN                57700
#define IDS_PROJECT_DELETE              57701

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
